name: Build Python EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdfplumber pandas pypdf openpyxl thefuzz

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --add-data "hungarian_names.txt;." heti_teljesitesi.py

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-exe
        path: dist
